# Generated by Django 5.2.5 on 2025-08-20 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Penulis')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Tahun Terbit')),
                ('genre', models.CharField(choices=[('fiksi', 'Fiksi'), ('komik', 'Komik'), ('motivasi', 'Motivasi')], default='fiksi', max_length=20, verbose_name='Genre')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Halaman')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='books/pdfs/', verbose_name='File PDF')),
                ('cover', models.ImageField(blank=True, help_text='Upload cover buku (opsional)', null=True, upload_to='books/covers/', verbose_name='Cover Buku')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorit')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to=settings.AUTH_USER_MODEL, verbose_name='Diupload oleh')),
            ],
            options={
                'verbose_name': 'Buku',
                'verbose_name_plural': 'Buku',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='books_book_title_d3218d_idx'), models.Index(fields=['author'], name='books_book_author_b941fe_idx'), models.Index(fields=['genre'], name='books_book_genre_4a7cdf_idx'), models.Index(fields=['favorite'], name='books_book_favorit_d63936_idx'), models.Index(fields=['created_at'], name='books_book_created_572b47_idx')],
            },
        ),
    ]
